# Generated by Django 3.2.8 on 2021-10-08 16:56

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Vinho')),
                ('cor', models.CharField(choices=[('T', 'Tinto'), ('R', 'Rose'), ('B', 'branco')], default='Tinto', max_length=20, verbose_name='Cor')),
                ('uva', models.CharField(choices=[('CS', 'Cabernet Sauvignon'), ('CF', 'Cabernet Franc'), ('PN', 'Pinot Noir'), ('ME', 'Merlot'), ('MA', 'Malbec'), ('RS', 'Riesling'), ('TN', 'Tannat'), ('CH', 'Chardonnay')], default='Cabernet', max_length=20, verbose_name='Uva')),
                ('acucar', models.CharField(choices=[('SC', 'Seco'), ('DS', 'Demi Sec'), ('SU', 'Suave'), ('DO', 'Doce'), ('NA', 'Nature'), ('EB', 'Extra Brut'), ('BR', 'Brut')], default='Seco', max_length=20, verbose_name='Teor de Açucar')),
                ('safra', models.IntegerField(verbose_name='Safra')),
                ('nacionalidade', models.CharField(choices=[('BR', 'Brasil'), ('AR', 'Argentina'), ('UR', 'Uruguai'), ('CH', 'Chile'), ('PO', 'Portugal'), ('ES', 'Espanha'), ('FR', 'França'), ('IN', 'Inglaterra'), ('IT', 'Itália'), ('AL', 'Alemanha'), ('SU', 'Suiça'), ('EU', 'Estados Unidos'), ('AF', 'África do Sul'), ('AU', 'Austrália')], default='Brasil', max_length=20, verbose_name='Nacionalidade')),
                ('vinicula', models.CharField(max_length=20, verbose_name='Vinícula')),
                ('alcool', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Teor de Álcool')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('reserva', models.CharField(choices=[('RE', 'Reserva'), ('NR', 'Não Reservado')], default='Reserva', max_length=20, verbose_name='Reserva')),
                ('tonalidade', stdimage.models.StdImageField(upload_to='tonalidade', verbose_name='Tonalidade')),
                ('img_rotulo', stdimage.models.StdImageField(upload_to='produto', verbose_name='Rótulo')),
                ('img_garrafa', stdimage.models.StdImageField(upload_to='garrafa', verbose_name='Garrafa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('promocao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Promoção')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('avaliacao', models.IntegerField(verbose_name='Avaliação')),
                ('num_avaliacoes', models.IntegerField(verbose_name='Número de avaliações')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
            ],
            options={
                'db_table': 'vinho',
            },
        ),
    ]
